import AppNavBar from "@/components/common/app_nav_bar/main";
import AppTheme from "@/components/common/app_theme";
import ProtectedRoute from "@/components/common/protected_route";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
      < >
        <ProtectedRoute/>
          {children}
      </>
    
  );
}
